version: "3.7"
services:
  web_store:
    container_name: web_store
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8442:80"
      - "8443:443"
    volumes:
      - "./web/www/:/var/www/html"
    networks:
      - store
    restart: unless-stopped
    depends_on:
      - db_store

  db_store:
    container_name: db_store
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: store
      MYSQL_USER: web
      MYSQL_PASSWORD: changeme2
    volumes:
      - "./database/data:/var/lib/mysql"
      - "./database/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./database/data.sql:/docker-entrypoint-initdb.d/2.sql"
    ports:
      - "9906:3306"
    networks:
      - store
    restart: always


networks:
  store:
    driver: bridge